"""Create initial transaction schema

Revision ID: 47a4346290ab
Revises:
Create Date: 2026-10-09 02:48:18.826541

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47a4346290ab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("first_category", sa.String(length=30), nullable=False),
        sa.Column("second_category", sa.String(length=30), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_history")
    # ### end Alembic commands ###
